[package]
name = "wasm"
version = "0.1.0"
authors = ["Oliver Gröning <o.groening@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
